### ISSUE TITLE
Slows down QDKS (2023)

### ISSUE THREAD

**Issue by jashcroft123** [HopeHarrison/PaneRelief#17]
https://github.com/JKISoftware/JKI-State-Machine-Editor/issues/119
See the above. The large number of VI put into Quickdrop/plugins folder (all but them in a subfolder) seems to slow down my QDKS whether or not the keypress has been assigned (namely ctrl + backspace)

**Comment by jashcroft123** [comment]
DNat got back to me. Turns out its a LV bug (Bug 2089884) See https://forums.ni.com/t5/Quick-Drop-Enthusiasts/Quick-Drop-Keyboard-Shortcut-Nattify-VI/m-p/4363877#M1282

**Comment by HopeHarrison** [comment]
Wow, this is great, I'm so glad there is a solution!

**Comment by jashcroft123** [comment]
This is a great tool by the way. Thanks!
