### ISSUE TITLE
Front Panel > Tools > PaneRelief

### ISSUE THREAD

**Issue by Ferrousduke** [HopeHarrison/PaneRelief#9]
Somehow I can see the PaneRelief.vi front panel opening when I try to launch it from Tools menu of the VI front panel. 'Ctrl + Spacebar' followed by 'Ctrl + a' works fine.

**Comment by HopeHarrison** [comment]
I'm not able to recreate this. It works for me from the tools menu.

What LabVIEW version are you seeing this on, and are you using the most recent version of PaneRelief?

**Comment by Ferrousduke** [comment]
I am using 2019 SP1 and I believe PaneRelief is also updated from VIPM.

**Comment by jimkring** [comment]
@Ferrousduke My guess is that you tried launching PaneRelief from the Project Explorer window, which doesn't work -- you have to launch it from a VI's Front Panel or Block Diagram window.

@HopeHarrison I dug into this and discovered a couple things:

1) Launching PaneRelief from the Project Explorer window should probably show a dialog stating that it needs to be run from a VI FP or BD.

2) The error that results actually causes the launcher to hang forever. Then, the second you try to run it, LabVIEW opens it's front panel (which is sort of off screen).

Here's a screenshot of what happens.

![image](https://user-images.githubusercontent.com/381432/99755252-268eee00-2a9f-11eb-9570-140156636a6c.png)

**Comment by HopeHarrison** [comment]
See if this works for you guys:
[jki_lib_panerelief-2.0.3.2.zip](https://github.com/HopeHarrison/PaneRelief/files/5584785/jki_lib_panerelief-2.0.3.2.zip)

And if you think the solution is okay (in linked pull request).
